CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255),
    profile_image_url VARCHAR(1024),
    provider VARCHAR(50) DEFAULT 'LOCAL' NOT NULL,
    role VARCHAR(50) DEFAULT 'USER' NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    balance NUMERIC(19, 2) DEFAULT 0.00 NOT NULL
);
